---
version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  event-api:
    image: astronomerinc/ap-event-api:latest
    depends_on:
      - kafka
    environment:
      EA_DEBUG_MODE: "false"
      EA_KAFKA_BROKERS: "kafka:9092"
      EA_KAFKA_TOPIC: "ingestion"
    ports:
      - "8080:8080"
      - "8081:8081"

  event-router:
    image: astronomerinc/ap-event-router:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      ER_DEBUG_MODE: "false"
      ER_KAFKA_BROKERS: "kafka:9092"
      ER_KAFKA_INPUT_TOPIC: "ingestion"
      ER_INTEGRATION_CONFIG_DIR: "."
    ports:
      - "8082:8081"
